services:
  portal:
    image: ghcr.io/gethomepage/homepage:v1.13.2
    container_name: portal
    restart: unless-stopped
    networks:
      caddy:
    depends_on:
      caddy:
        condition: service_started
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${DOMAIN},portal.${DOMAIN},homepage.${DOMAIN},portal:3000
    volumes:
      - ./configs/homepage:/app/config
