title: Datamancy
description: Self-hosted service dashboard
target: _self
hideVersion: true
showStats: false
statusStyle: dot
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
layout:
  Communication:
    style: row
    columns: 3
  Knowledge & Files:
    style: row
    columns: 3
  Work:
    style: row
    columns: 4
  Home & Media:
    style: row
    columns: 3
  Local:
    style: row
    columns: 2
